#!/bin/bash
# Run the builder. Locally installs prereqs needed by the builder.

PACKER_VERSION=0.5.2
PACKER_BASE_URL="https://dl.bintray.com/mitchellh/packer"

HERE=$(cd "$(dirname "$0")"; pwd)
TEMPLATES="$HERE/templates"
IMAGES="$HERE/images"
DATA="$HERE/.data"
CACHE="$DATA/cache"
TMP="$DATA/tmp"
PACKER="$DATA/packer"
LOG="$DATA/run.log"

log() {
	if [ $# -eq 0 ]; then
		cat >> "$LOG"
	else
		echo "$@" >> "$LOG"
	fi
}

stderr() {
	echo "$@" >&2
}

info() {
	stderr -e "\e[0;32m>>\e[0m" "$@"
	log ">>" "$@"
}

error() {
	stderr -e "\e[0;31m>>\e[0m" "$@"
	log ">>" "$@"
}

fatal() {
	error "$@"
	exit 1
}

init() {
	rm -f "$LOG"
	mkdir -p "$TMP" || fatal "Failed to create temporary directory."
	mkdir -p "$IMAGES" || fatal "Failed to create images directory."
}

packer_version() {
	# Print the current packer version or an empty string if not installed
	if [ -x "$PACKER/packer" ]; then
		"$PACKER/packer" --version | sed 's/.*v//' 2> /dev/null
	fi
}

packer_install() {
	# Install packer if it's not present.
	PATH="$PACKER:$PATH"
	test "$(packer_version)" == "$PACKER_VERSION" && return 0

	info "Packer: Initializing directories."
	test -e "$PACKER" && rm -rf "$PACKER"
	mkdir -p "$PACKER" | log || fatal "Packer: Creation of '$PACKER' failed."
	local platform=$(uname -s | tr '[:upper:]' '[:lower:]')
	local url="$PACKER_BASE_URL/${PACKER_VERSION}_${platform}_amd64.zip"
	local dest="$TMP/packer_${PACKER_VERSION}_${platform}_amd64.zip"
	if ! [ -e "$dest" ]; then
		info "Packer: Downloading to '$dest'."
		wget -q "$url" -O "$dest" | log || fatal "Packer: Download from '$url' failed."
	else
		info "Packer: Using cached archive at '$dest'."
	fi
	info "Packer: Installing to '$PACKER'."
	cd "$PACKER" || fatal "Packer: Failed to cd to '$PACKER'."
	unzip -o "$dest" 2>&1 | log || fatal "Packer: Failed to extract archive."
}

usage() {
	test -n "$1" && error "$@"
	stderr "usage: build IMAGE VERSION [NAME=VALUE [...]]"
	test -n "$1" && exit 1
}

build() {
	# usage: build IMAGE VERSION [NAME=VALUE [...]]
	test -n "$1" || usage "No image template provided."
	test -n "$2" || usage "No version provided."
	local name="$1"
	local version="$2"
	shift; shift

	local vars=()
	vars+=(-var "version=$version")
	vars+=(-var "images=$IMAGES")
	for var in "$@"; do
		vars+=(-var "$var")
	done

	local image="$TEMPLATES/$name"
	test -d "$image" || fatal "Image template '$name' not found."
	cd "$image" || fatal "Failed to cd to '$image'."
	test -f template.json || fatal "Image template '$name' is missing template.json."
	PACKER_CACHE_DIR="$CACHE" packer build "${vars[@]}" template.json | tee -a "$LOG"
}

init
packer_install
build "$@"
